[book]
authors = ["Boog900"]
language = "en"
multilingual = false
src = "src"
title = "The Monero Book"

[build]
create-missing = false

[output.html]
mathjax-support = true
additional-css = ["svgbob.css"]

[preprocessor.svgbob]
